// <auto-generated />
using System;
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WeatherApp.DataModel.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190808193423_migr1")]
    partial class migr1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherApp.DataModel.Models.Weather", b =>
                {
                    b.Property<int>("WeatherId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atmosphere");

                    b.Property<int?>("H");

                    b.Property<double>("Humidity");

                    b.Property<int?>("OverCast");

                    b.Property<int?>("SpeedWind");

                    b.Property<double>("Td");

                    b.Property<double>("Temperature");

                    b.Property<DateTime>("TimeMeasuring");

                    b.Property<string>("VW");

                    b.Property<string>("WeatherCondition");

                    b.Property<string>("WeatherDirectionWind");

                    b.HasKey("WeatherId");

                    b.ToTable("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
